/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _checkbox_unchecked_h_
#define _checkbox_unchecked_h_
//---------------------------------------------------------------------------------
extern const unsigned char checkbox_unchecked[];
extern const int checkbox_unchecked_size;
//---------------------------------------------------------------------------------
#endif //_checkbox_unchecked_h_
//---------------------------------------------------------------------------------
