/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _checkbox_checked_h_
#define _checkbox_checked_h_
//---------------------------------------------------------------------------------
extern const unsigned char checkbox_checked[];
extern const int checkbox_checked_size;
//---------------------------------------------------------------------------------
#endif //_checkbox_checked_h_
//---------------------------------------------------------------------------------
