/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cursor_default_h_
#define _cursor_default_h_
//---------------------------------------------------------------------------------
extern const unsigned char cursor_default[];
extern const int cursor_default_size;
//---------------------------------------------------------------------------------
#endif //_cursor_default_h_
//---------------------------------------------------------------------------------
