/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _helvetica_h_
#define _helvetica_h_
//---------------------------------------------------------------------------------
extern const unsigned char helvetica[];
extern const int helvetica_size;
//---------------------------------------------------------------------------------
#endif //_helvetica_h_
//---------------------------------------------------------------------------------
