/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _keyboard_tex_h_
#define _keyboard_tex_h_
//---------------------------------------------------------------------------------
extern const unsigned char keyboard_tex[];
extern const int keyboard_tex_size;
//---------------------------------------------------------------------------------
#endif //_keyboard_tex_h_
//---------------------------------------------------------------------------------
