/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _logo_wiivnc_h_
#define _logo_wiivnc_h_
//---------------------------------------------------------------------------------
extern const unsigned char logo_wiivnc[];
extern const int logo_wiivnc_size;
//---------------------------------------------------------------------------------
#endif //_logo_wiivnc_h_
//---------------------------------------------------------------------------------
