/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _textbox_back_h_
#define _textbox_back_h_
//---------------------------------------------------------------------------------
extern const unsigned char textbox_back[];
extern const int textbox_back_size;
//---------------------------------------------------------------------------------
#endif //_textbox_back_h_
//---------------------------------------------------------------------------------
