/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _wiibutton_h_
#define _wiibutton_h_
//---------------------------------------------------------------------------------
extern const unsigned char wiibutton[];
extern const int wiibutton_size;
//---------------------------------------------------------------------------------
#endif //_wiibutton_h_
//---------------------------------------------------------------------------------
